### ISSUE TITLE
GSOC Application for 2018

### ISSUE THREAD

**Issue by mnarayan** [skggm/skggm#107]
See information here
https://summerofcode.withgoogle.com/
https://opensource.googleblog.com/2018/01/seeking-open-source-projects-for-google.html

Discuss. Possible organizations could be 
- [INCF](https://summerofcode.withgoogle.com/archive/2017/organizations/6593178794721280/) 
> We have a discussion forum for mentors and interested students. To be added, email gsoc@incf.org with a description of which project you are interested in.
>
> If you have general questions about INCF and our participation in GSoC, please contact us on gsoc@incf.org., 
Current ideas [here](https://www.incf.org/collaborate/tool-development/google-summer-of-code/gsoc-2018-project-ideas)
- [NumFocus](https://summerofcode.withgoogle.com/archive/2017/organizations/6630791836598272/) 
or 
- [Python Software Foundation](https://summerofcode.withgoogle.com/archive/2017/organizations/5370985721102336/).

**Comment by jasonlaska** [comment]
Looks like the deadline passed some time ago.  Let me know if you want to try again in 2019.
