### ISSUE TITLE
Using GraphicalLasso for consistency with scikit-learn API

### ISSUE THREAD

**Issue by mnarayan** [skggm/skggm#109]
Going forward `GraphLasso` is going to be `GraphicalLasso` to prevent ambiguity and confusion in the literature. https://github.com/scikit-learn/scikit-learn/pull/10078

I never did understand why the graphical lasso was `GraphLasso` in sklearn. I guess it was an inadvertent mistake. I'm happy to see the name will be fixed. 

This will affect how our classes `QUICGraphLasso` and its derivatives are perceived. To stay consistent, we should do the same.

**Comment by jasonlaska** [comment]
Ok,

I think we can update the names and then provide some aliases to the old signatures.  I'll do that as part of my cleanup this weekend.

**Comment by jasonlaska** [comment]
Addressed in #114
