### ISSUE TITLE
Unexpected QuicGraphLassoEBIC behaviour

### ISSUE THREAD

**Issue by davesl** [skggm/skggm#110]
I've been observing some strange behavior with the _QuicGraphLassoEBIC_ function. Perhaps this is a misunderstanding of mine from the documentation but I will try to explain.

As far as I understand, when using _QuicGraphLassoEBIC_ a `lam` parameter is specified which is then scaled to the data if `auto_scale=True`. Setting the `path` parameter to an integer should then generate a grid of regularization parameters to test and score using the EBIC criteria.

However, when I run this function on my data the resulting model class does not contain any attributes that would suggest multiple lambdas have been tested - no EBIC scores for each lambda tested, only a single precision matrix etc. Furthermore, if I use the `ebic_select `method on this model I get the error "EBIC requires multiple models to select from".

Finally, the selected precision matrix and 'optimal' lambda appears to be highly dependent on the size of the path variable - selecting `path=100`, `path=1000` or `path=10000` results in very different models and regularization parameters.

What am I missing here? How exactly does the path parameter determine the lambdas to test and why am I seeing these inconsistencies?

Thanks a lot.

**Comment by mnarayan** [comment]
Model selection methods such as the EBIC only choose from an available set of models. The number of models provided depend on the resolution of the regularization path and the complexity/dimensionality of your problem. 

Hypothetically if you were to specify a grid of parameters at the finest level such that between any two consecutive regularization parameters only one edge and no more than one edge enters or leaves the path then you will basically specify as many models as there are edges in the network. This is the largest possible set of models to choose from. When you have coarser regularization paths, it is always possible in practice that your pool of models are too small and don't approximate the true model well. A second issue however, is that EBIC scores are estimates and will have some noise, thus there is some possibility of not choosing the exact same model as "nearby" models will be statistically indistinguishable.  

However, depending on the data your are working with, the above might either be computationally infeasible or data is so noisy that there are many statistically indistinguishable models.

I will be out of office for a few weeks, so might be slow to respond.
