### ISSUE TITLE
Error when Install on macos

### ISSUE THREAD

**Issue by iccentt** [skggm/skggm#117]
When I tried to install on MacOS, error appear with 'gcc':
```
inverse_covariance/pyquic/pyquic.cpp:828:14: fatal error: 'complex' file not found
        #include <complex>
                 ^~~~~~~~~
    2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1
```
Can you tell me how to solve this?

**Comment by jasonlaska** [comment]
Does this help? https://github.com/healpy/healpy/issues/284#issuecomment-146456205

**Comment by iccentt** [comment]
@jasonlaska I tried to upgrade llvm, but the error still persisted.
Any ideas?

**Comment by jasonlaska** [comment]
It looks like the "complex" library is not available or cannot be found.  I'm not sure why that would be.  You have XCode and developer tools installed?

**Comment by iccentt** [comment]
@jasonlaska I have XCode (actually updated and reinstall after upgrade to Mojave) and other.
It seems that Mojave not allow to run: xcode-select --install (due to already installed).
```
llvm ver: 7.0.0
clang ver: clang-1000.11.45.5
```

**Comment by iccentt** [comment]
Another information: I tried on Windows & latest Anaconda 5.3 (python 3.7) with Visual C++ 14.
It also failed.
Maybe skggm only tested on Ubuntu.

**Comment by jasonlaska** [comment]
I am using skggm on MacOSX El Capitan 10.11.6 and I believe it also worked on the previous OS.  You're right though, haven't tried yet on Mohave.

The ticket here has a similar issue and says to try absolute imports in cpp file: https://trac.macports.org/ticket/57430

There is probably a more general solution for letting the compiler know where the libraries live, maybe a link or envvar broke in the upgrade.

**Comment by jasonlaska** [comment]
And possible this note is related: 

- https://stackoverflow.com/questions/50780183/cannot-install-brew-on-mojave-with-xcode10

- https://apple.stackexchange.com/questions/337940/why-is-usr-include-missing-i-have-xcode-and-command-line-tools-installed-moja

**Comment by jasonlaska** [comment]
If those notes above about Mojave and the developer tools don't work, you can also try docker, we have an example docker file with ubuntu here: https://github.com/neuroquant/jf2016-skggm/blob/master/Dockerfile

**Comment by iccentt** [comment]
@jasonlaska I have just got another update for Xcode from Apple this morning and successfully install skggm. I guess they fixed their issue.
Thanks for your help.

**Comment by yandustc** [comment]
@iccentt How did you finally installed skggm? I am struggling with installing skggm on Mojave. Could you give me some hints? Thank you!

**Comment by iccentt** [comment]
@yandustc check install Xcode (after update to Mojave, you need to open it for some agreements) or any updates (from App Store). The latest update helped me to solve this problem.

**Comment by jasonlaska** [comment]
Hi @iccentt it sounds like the solution here is to get the most recent update of apple's developer tools. Thank you @yandustc for investigating.
