### ISSUE TITLE
Error when Install on Windows

### ISSUE THREAD

**Issue by westzhicanchen** [skggm/skggm#118]
Hi developers:
I have previously installed Numpy, Scipy and Cython, but when I followed the instructions to install this package through Anaconda (pip install skggm) on my Windows 10, but I get the following error:

building 'pyquic.pyquic' extension
  error: Don't know how to compile inverse_covariance/pyquic/QUIC.C

  ----------------------------------------
  Failed building wheel for skggm

I wonder if you know what's going on?

**Comment by jasonlaska** [comment]
Hi @westzhicanchen, I'm not sure that this package will work directly on Windows as QUIC requires several standard c/posix libraries (although I am not super familiar with build chains on windows).  I recommend that you run this in a linux virtual machine on your machine, if possible.

**Comment by westzhicanchen** [comment]
Hi Jason, thanks for reply. I'm not quite sure if it's worthy to get a virtual Linux Machine. So, I wonder if you know any easier ways to fix this problem? Actually, the most I'm concerned is the adaptive Graphical LASSO function, do you know any similar packages or any other ways? 

Much Appreciated!

**Comment by jasonlaska** [comment]
If you can find a windows-compatible implementation of the graphical lasso that supports matrix penalties, then you can easily adapt https://github.com/skggm/skggm/blob/develop/inverse_covariance/adaptive_graph_lasso.py for it as the adaptive graph lasso is more of a meta-algorithm.

There are some resources in the readme of this repo for original QUIC implementations.
