### ISSUE TITLE
quic is not deterministic

### ISSUE THREAD

**Issue by wdevazelhes** [skggm/skggm#121]
quic can give different results for the same input, and setting numpy random state does not fix the problem. Is there a potential source for this indetermination ? This makes it difficult for an estimator that uses skggm to be considered as scikit-learn's estimator (i.e. pass the `check_estimator` test), because some tests check that the estimator is deterministic

Example:
```python
from inverse_covariance import quic
import numpy as np

np.random.seed(42)
A = np.random.randn(20, 20)
A = A.dot(A.T)

np.random.seed(42)
A_1, _, _, _, _, _ = quic(A, lam=0.01)

np.random.seed(42)
A_2, _, _, _, _, _ = quic(A, lam=0.01)

np.testing.assert_allclose(A_1, A_2)
``` 

Returns:
```
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 99.0%)
 x: array([ 0.985128,  0.181885,  0.414247, -0.473431, -0.483563,  0.027897,
        0.292402,  0.116016, -0.177139, -0.395764,  0.217043, -0.367557,
       -0.233921,  0.225825, -0.072036,  0.387505, -0.959885,  0.084411,...
 y: array([ 0.985154,  0.181885,  0.414257, -0.473441, -0.483574,  0.027899,
        0.292409,  0.116016, -0.177139, -0.395786,  0.217051, -0.367555,
       -0.233921,  0.225839, -0.072036,  0.387511, -0.959911,  0.084411,...
```

**Comment by jasonlaska** [comment]
Hi @wdevazelhes thanks for bringing this to our attention. I was aware that the sklearn general tests were not passing deterministically (and I think our tests are currently broken, I need to look into it).  @mnarayan do you have any idea why QUIC would produce non-deterministic behavior?

**Comment by jasonlaska** [comment]
This was the only instance of `rand()` I could find in quic.c: https://github.com/skggm/skggm/blob/develop/inverse_covariance/pyquic/QUIC.C#L322, which could be stabilized by setting the seed in c with `srand(seed)`.  I'm not sure if this is the source of the non-deterministic outputs but certainly could be.  (Seems the original authors were fixing the seed: https://github.com/skggm/skggm/blob/develop/inverse_covariance/pyquic/QUIC.C#L240)

**Comment by mnarayan** [comment]
I will look into this and get back.

**Comment by mnarayan** [comment]
Indeed, i believe that `srand(1)` is usually left uncommented by QUIC authors in their other algorithms. This is probably a mistake that wasn't caught because tolerance levels were smaller when debugging.

**Comment by mnarayan** [comment]
Hmm, I just tried fixing the random seed. The following test `test_integration_quic_graphical_lasso_ebic`from `inverse_covariance/tests/quic_graph_lasso_test.py` fails
```
>       assert_allclose(expected, result_vec, atol=1e-1, rtol=1e-1)
E       AssertionError: 
E       Not equal to tolerance rtol=0.1, atol=0.1
E       
E       (mismatch 100.0%)
E        x: array([3.162278, 3.162278, 0.911163])
E        y: array([1.583243, 9.062612, 0.011498])
```
This could be related to following overflow warnings 
```
inverse_covariance/tests/common_test.py::test_quic_graphical_lasso_ebic
  /usr/local/lib/python3.6/dist-packages/numpy/linalg/linalg.py:1965: RuntimeWarning: overflow encountered in slogdet
    sign, logdet = _umath_linalg.slogdet(a, signature=signature)
```

**Comment by mnarayan** [comment]
Ok so using `srand(1)` seems to fix indeterministic numerical errors. 

However  `check_estimator` tests in skggm's [common_test.py](https://github.com/skggm/skggm/blob/develop/inverse_covariance/tests/common_test.py#L12) still fails due to check2d1sample test in [sklearn](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/estimator_checks.py#L828). Here is the `check_estimator` test that fails

```
def check_fit2d_1sample(name, estimator_orig):
    # Check that fitting a 2d array with only one sample either works or
    # returns an informative message. The error message should either mention
    # the number of samples or the number of classes.

```

It triggers the following errors, which are the identical to why travis has been failing [recently](https://travis-ci.org/skggm/skggm/builds/487525235#L896)

```bash
E       ValueError: not enough values to unpack (expected 2, got 0)

inverse_covariance/quic_graph_lasso.py:56: ValueError
_______________________________________________ test_quic_graphical_lasso_ebic ________________________________________________

    def test_quic_graphical_lasso_ebic():
>       return check_estimator(QuicGraphicalLassoEBIC)

```

**Comment by jasonlaska** [comment]
@wdevazelhes for the time being until we make a new release, you can have your project point to a0ed406586c4364ea3297a658f415e13b5cbdaf8 (the latest `develop`) to get this version with a fixed seed.

**Comment by wdevazelhes** [comment]
Great ! Thanks a lot !
