### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.joblib'

### ISSUE THREAD

**Issue by raghuramdr** [skggm/skggm#124]
Hi, when I try to import `inverse_covarance` in skggm, the following error pops up. 

```
from inverse_covariance import QuicGraphicalLasso
 from sklearn.externals.joblib import Parallel, delayed
ModuleNotFoundError: No module named 'sklearn.externals.joblib'
```
The issue is because sklearn.externals.joblib is deprecated from scikit-learn 0.21 onwards and has been removed in 0.23 of scikit-learn. Downgrading `scikit-learn` to 0.20.1 removes the error message. While, v0.21.1 of `scikit-learn` doesn't throw up the error, it does throw a deprecation warning. 

This is something you might want to update in the `requirements.txt` and also in the `setup.py` file.

EDIT: I am using Python 3.6.10 if it is relevant.

**Comment by sunidhibatra** [comment]
Hey, could you solve this one. Please let me know how to solve this error

**Comment by mnarayan** [comment]
> Hey, could you solve this one. Please let me know how to solve this error

Thanks @sunidhibatra

**Comment by mnarayan** [comment]
PR #127 fixing this issue has been accepted. 

cc: @raghuramdr @sunidhibatra @wdevazelhes
