### ISSUE TITLE
Move functions in simulation_example.py to data generation class

### ISSUE THREAD

**Issue by mnarayan** [skggm/skggm#61]
The simplest data generation class needs the following functionality: 
- Adjacency generation according to erdos-renyi, or banded network structure types
- Converting an adjacency matrix into a proper precision and covariance matrix
- Simulating from a multivariate probability distribution (initially normal, but later one maybe t-variate  and others as well). 

https://github.com/skggm/skggm/blob/feature/add-simulation-examples/examples/simulate_networks.py

**Comment by jasonlaska** [comment]
For network metrics blog post.
I need
a. A simple version of the data generation class with at 3 graph types.
b. A set of methods for different metrics
- Monte-carlo class with random number state tracking + a + b
