### ISSUE TITLE
TypeError: expected bytes, str found

### ISSUE THREAD

**Issue by TianpeiLuke** [skggm/skggm#83]
Hi, 
  I was trying to run the convergence_comparison.py in the examples. I run across this issue. 

Traceback (most recent call last):
  File "convergence_comparison.py", line 28, in <module>
    vals = quic(Shat, .004, mode='default', tol=1e-6, max_iter=1000, Theta0=np.eye(Shat.shape[0]), Sigma0=np.eye(Shat.shape[0]), path=None, msg=1)
  File "/home/tianpei/anaconda3/lib/python3.5/site-packages/skggm-0.2.6-py3.5-linux-x86_64.egg/inverse_covariance/quic_graph_lasso.py", line 121, in quic
    Theta, Sigma, opt, cputime, iters, dGap)
  File "inverse_covariance/pyquic/pyquic.pyx", line 12, in pyquic.pyquic.quic (inverse_covariance/pyquic/pyquic.cpp:1644)
TypeError: expected bytes, str found

what is wrong with it.  I was using python 3.5. It seems to be a problem of python 3

**Comment by jasonlaska** [comment]
Hi Tianpei,

Questions:
- which OS/platform are you running on?
- where you able to run any of the other demos 

I haven't tested this with python3 yet, but I'll make a ticket to make sure it runs there in the future.  If you find the solution in the interim, please report it here.

cheers

**Comment by TianpeiLuke** [comment]
A:
 1. I was running on ubuntu 16.04. using anaconda, with python 3.5
 2. All demos related to quic stops due to the issue with pyquic.cpp

I actually realized that this is due to the use of python 3, since it works when I run it on my laptop with python 2.7.

**Comment by TianpeiLuke** [comment]
Hi, Thank you for quick reply. I also realized that all print " .. " commands should be changed to print("..") if needs to run with Python 3. That is a small issue.

**Comment by TianpeiLuke** [comment]
I think this doc is useful. 
[](http://cython.readthedocs.io/en/latest/src/tutorial/strings.html)

**Comment by jasonlaska** [comment]
Hi @TianpeiLuke, 

I've updated some things so that the package will work in python3.  Thanks for the tip above, I've used that as well as a few other minor edits.  The example files should now be compatible as well.

These changes will appear in the next release, but you can get them now by pulling the `develop` branch in this repo and runnign setup.py or compiling `pyquic` with `make python3`.

Please let me know if you continue to find issues.

thanks,
Jason
