### ISSUE TITLE
Add additional tests to check initialization of sample correlation matrix

### ISSUE THREAD

**Issue by mnarayan** [skggm/skggm#97]
Given the new features that adds rank correlation options to `init_method` for `quic_graph_lasso.py` we need more tests. 

From discussion of PR #92 
> Would be good to add a few tests in https://github.com/skggm/skggm/blob/develop/inverse_covariance/tests/quic_graph_lasso_test.py that use the new initializers. Should be as simple as adding more examples to the pytest.parameterize arrays but with modified inputs/outputs.

**Comment by jasonlaska** [comment]
I added these.
