### ISSUE TITLE
Cannot import QuicGraphLasso 3.5 , get another error with 2.7.

### ISSUE THREAD

**Issue by charles2588** [skggm/skggm#98]
>>> from inverse_covariance import QuicGraphLasso
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/charles/.local/lib/python3.5/site-packages/inverse_covariance/__init__.py", line 2, in <module>
    from .inverse_covariance import (
  File "/Users/charles/.local/lib/python3.5/site-packages/inverse_covariance/inverse_covariance.py", line 78
    print 'Warning: Path must be sorted largest to smallest.'
                                                            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by jasonlaska** [comment]
Huh interesting, doesn't look like the last release included those python3 fixes.   For now try pulling the latest `develop` branch (see https://github.com/skggm/skggm/blob/develop/inverse_covariance/inverse_covariance.py#L80)  and installing manually (see instructions in Readme.md).  

We should be release a new version shortly with a few extra tools so I'll keep you posted.

**Comment by jasonlaska** [comment]
Hi @charles2588, just updated to skggm 2.7;  you can find it at https://github.com/skggm/skggm/releases, https://pypi.python.org/pypi/skggm/0.2.7, or pull it with `pip3 install skggm --upgrade`.   This should fully support python3.

Let me know if your issues persist, we would love to make sure folks can use this package (still working out the kinks).

cheers.
